### ISSUE TITLE
Riksdagsprotokoll 6 – Ord som samförekommer med ett koncept

### ISSUE THREAD

**Issue by fredrik1984** [welfare-state-analytics/welfare_state_analytics#81]
Skapa ~~en Jupyter-sida~~ __CLI program som genererar data__ för att se frekvensförändring av samförekommande ord till ett valt nyckelord. Denna funktion påminner mycket om det ordfönsterdata som vi använde oss av hösten 2019 då vi gjorde nätverksanalys av det politiska.

- Välj tidsperiod (t ex 1945–1989)
- Välj korpus (med/utan stoppordslista, lemmatiserat, icke-lemmatiserade etc)
- Välj en nyckelord (t ex "information")
- Välj storlek på ordfönster (t ex 3 ord före och efter nyckelordet)
- Generera en tabell med topplistor över samförekommande ord till nyckelordet – totalt för hela perioden eller för varje år. För att kunna jämföra mellan olika nyckelord ska det också finnas en funktion som gör att listorna med samförekommande ord är normaliserade
- Generera ett spreadsheet som innehåller samförekommande ord under den givna tidsperioden, med ett normaliserat viktvärde. Detta spreadsheet kan sedan vara ett underlag för att importera till Gephi.

**Comment by roger-mahler** [comment]
The feature that create the data requested in this task has been implemented in `humlab-penelope` (release 0.2.17). The data generation is a long-running task, and for a bigger corpus, such as this one, and the process takes ca: 40 minutes. It is hence not suitable as a feature available via a Jupyter interface. Instead it has been implemented as a callable function in the `penelope` package API, and as a command line CLI program `concept_cooccurrence` available when `penelope` is installed.

Follow these steps to install the `concept_cooccurrence` CLI program:

Prerequisites
--------------
 - Python ^3.8 Run `python --version` to determine the current version. The use of [pyenv](https://github.com/pyenv/pyenv#installation) is recommended if you don't have Python 3.8 since it allows for easy switching between different Python versions (use [automatic installer](https://github.com/pyenv/pyenv-installer)). 
 - Poetry. Poetry is a Python package manager (comparable to `pipenv`). This program is needed to install  `concept_cooccurrence` in a separate isolated environment. See [this link](https://github.com/pyenv/pyenv-installer) on how to install Poetry. Not that Poetry should be installed after Python 3.8 is activated.

Note that an alternative is to use Humlab's servers to run the program.

Install the CLI
--------------

1. Create a local folder (e.g. `concept_cooccurrence`)
2. Open a terminal in the very same folder
3. Run `poetry init` to create a new environment
4. Run `poetry add humlab-penelope`
5. Run `poetry install`

Run the CLI
--------------
1. Open a terminal in the folder where `concept_cooccurrence` was installed
2

**Comment by roger-mahler** [comment]
```bash
concept_cooccurrence --concept=information --context-width=4 --partition-key=year --pos-includes='|NN|' --lemmatize --min-word-length=2 --filename-field='year:prot\_(\d{4}).*' --no-concept test_data/riksdagens-protokoll.1920-2019.zip information_4_NN.zip
```

**Comment by roger-mahler** [comment]
```man
┌─[11:22:33]─[roger@p2]─[~/source/concept-cooccurrence]
└──>  (poetry) λ concept_cooccurrence --help
Usage: concept_cooccurrence [OPTIONS] INPUT_FILENAME OUTPUT_FILENAME

Options:
  -c, --concept TEXT              Concept
  --no-concept                    Filter out concept word
  -w, --context-width INTEGER     Width of context on either side of concept.
                                  Window size = 2 * context_width + 1

  -p, --partition-key TEXT        Pertition key(s)
  -i, --pos-includes TEXT         List of POS tags to include e.g. "|NN|JJ|".
  -x, --pos-excludes TEXT         List of POS tags to exclude e.g.
                                  "|MAD|MID|PAD|".

  -b, --lemmatize / --no-lemmatize
                                  Use word baseforms
  -l, --to-lowercase / --no-to-lowercase
                                  Lowercase words
  -r, --remove-stopwords [swedish|english]
                                  Remove stopwords using given language
  -m, --min-word-length INTEGER RANGE
                                  Min length of words to keep
  -s, --keep-symbols / --no-keep-symbols
                                  Keep symbols
  -n, --keep-numerals / --no-keep-numerals
                                  Keep numerals
  --only-alphabetic               Keep only tokens having only alphabetic
                                  characters

  --only-any-alphanumeric         Keep tokens with at least one alphanumeric
                                  char

  -f, --filename-field TEXT       Fields to extract from document name
  --help                          Show this message and exit.
```
